// Code generated by protoc-gen-go.
// source: tapestry_rpc.proto
// DO NOT EDIT!

/*
Package tapestry is a generated protocol buffer package.

It is generated from these files:
	tapestry_rpc.proto

It has these top-level messages:
	Ok
	IdMsg
	DataBlob
	Key
	NodeMsg
	NextHop
	Registration
	FetchedLocations
	Neighbors
	MulticastRequest
	TransferData
	BackpointerRequest
	LeaveNotification
*/
package tapestry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ok struct {
	Ok     bool   `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
}

func (m *Ok) Reset()                    { *m = Ok{} }
func (m *Ok) String() string            { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()               {}
func (*Ok) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Ok) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *Ok) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type IdMsg struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Level   int32    `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}
func (m *IdMsg) Reset()                    { *m = IdMsg{} }
func (m *IdMsg) String() string            { return proto.CompactTextString(m) }
func (*IdMsg) ProtoMessage()               {}
func (*IdMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IdMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
type DataBlob struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *DataBlob) Reset()                    { *m = DataBlob{} }
func (m *DataBlob) String() string            { return proto.CompactTextString(m) }
func (*DataBlob) ProtoMessage()               {}
func (*DataBlob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DataBlob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DataBlob) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Key struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type NodeMsg struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *NodeMsg) Reset()                    { *m = NodeMsg{} }
func (m *NodeMsg) String() string            { return proto.CompactTextString(m) }
func (*NodeMsg) ProtoMessage()               {}
func (*NodeMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NodeMsg) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NextHop struct {
	Next    *NodeMsg `protobuf:"bytes,1,opt,name=next" json:"next,omitempty"`
	ToRemove []*NodeMsg `protobuf:"bytes,2,rep,name=toRemove" json:"toRemove,omitempty"`
}

func (m *NextHop) Reset()                    { *m = NextHop{} }
func (m *NextHop) String() string            { return proto.CompactTextString(m) }
func (*NextHop) ProtoMessage()               {}
func (*NextHop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NextHop) GetNext() *NodeMsg {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *NextHop) GetToRemove() []*NodeMsg {
	if m != nil {
		return m.ToRemove
	}
	return nil
}

type Registration struct {
	FromNode *NodeMsg `protobuf:"bytes,1,opt,name=fromNode" json:"fromNode,omitempty"`
	Key      string   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
}

func (m *Registration) Reset()                    { *m = Registration{} }
func (m *Registration) String() string            { return proto.CompactTextString(m) }
func (*Registration) ProtoMessage()               {}
func (*Registration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Registration) GetFromNode() *NodeMsg {
	if m != nil {
		return m.FromNode
	}
	return nil
}

func (m *Registration) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type FetchedLocations struct {
	IsRoot bool       `protobuf:"varint,1,opt,name=isRoot" json:"isRoot,omitempty"`
	Values []*NodeMsg `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
}

func (m *FetchedLocations) Reset()                    { *m = FetchedLocations{} }
func (m *FetchedLocations) String() string            { return proto.CompactTextString(m) }
func (*FetchedLocations) ProtoMessage()               {}
func (*FetchedLocations) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FetchedLocations) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *FetchedLocations) GetValues() []*NodeMsg {
	if m != nil {
		return m.Values
	}
	return nil
}

type Neighbors struct {
	Neighbors []*NodeMsg `protobuf:"bytes,1,rep,name=neighbors" json:"neighbors,omitempty"`
}

func (m *Neighbors) Reset()                    { *m = Neighbors{} }
func (m *Neighbors) String() string            { return proto.CompactTextString(m) }
func (*Neighbors) ProtoMessage()               {}
func (*Neighbors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Neighbors) GetNeighbors() []*NodeMsg {
	if m != nil {
		return m.Neighbors
	}
	return nil
}

type MulticastRequest struct {
	NewNode *NodeMsg `protobuf:"bytes,1,opt,name=newNode" json:"newNode,omitempty"`
	Level   int32    `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}

func (m *MulticastRequest) Reset()                    { *m = MulticastRequest{} }
func (m *MulticastRequest) String() string            { return proto.CompactTextString(m) }
func (*MulticastRequest) ProtoMessage()               {}
func (*MulticastRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MulticastRequest) GetNewNode() *NodeMsg {
	if m != nil {
		return m.NewNode
	}
	return nil
}

func (m *MulticastRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type TransferData struct {
	From *NodeMsg              `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Data map[string]*Neighbors `protobuf:"bytes,2,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *TransferData) Reset()                    { *m = TransferData{} }
func (m *TransferData) String() string            { return proto.CompactTextString(m) }
func (*TransferData) ProtoMessage()               {}
func (*TransferData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *TransferData) GetFrom() *NodeMsg {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransferData) GetData() map[string]*Neighbors {
	if m != nil {
		return m.Data
	}
	return nil
}

type BackpointerRequest struct {
	From  *NodeMsg `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Level int32    `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
}

func (m *BackpointerRequest) Reset()                    { *m = BackpointerRequest{} }
func (m *BackpointerRequest) String() string            { return proto.CompactTextString(m) }
func (*BackpointerRequest) ProtoMessage()               {}
func (*BackpointerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BackpointerRequest) GetFrom() *NodeMsg {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *BackpointerRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type LeaveNotification struct {
	From        *NodeMsg `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	Replacement *NodeMsg `protobuf:"bytes,2,opt,name=replacement" json:"replacement,omitempty"`
}

func (m *LeaveNotification) Reset()                    { *m = LeaveNotification{} }
func (m *LeaveNotification) String() string            { return proto.CompactTextString(m) }
func (*LeaveNotification) ProtoMessage()               {}
func (*LeaveNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }


func (m *LeaveNotification) GetFrom() *NodeMsg {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *LeaveNotification) GetReplacement() *NodeMsg {
	if m != nil {
		return m.Replacement
	}
	return nil
}

func init() {
	proto.RegisterType((*Ok)(nil), "tapestry.Ok")
	proto.RegisterType((*IdMsg)(nil), "tapestry.IdMsg")
	proto.RegisterType((*DataBlob)(nil), "tapestry.DataBlob")
	proto.RegisterType((*Key)(nil), "tapestry.Key")
	proto.RegisterType((*NodeMsg)(nil), "tapestry.NodeMsg")
	proto.RegisterType((*NextHop)(nil), "tapestry.NextHop")
	proto.RegisterType((*Registration)(nil), "tapestry.Registration")
	proto.RegisterType((*FetchedLocations)(nil), "tapestry.FetchedLocations")
	proto.RegisterType((*Neighbors)(nil), "tapestry.Neighbors")
	proto.RegisterType((*MulticastRequest)(nil), "tapestry.MulticastRequest")
	proto.RegisterType((*TransferData)(nil), "tapestry.TransferData")
	proto.RegisterType((*BackpointerRequest)(nil), "tapestry.BackpointerRequest")
	proto.RegisterType((*LeaveNotification)(nil), "tapestry.LeaveNotification")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TapestryRPC service

type TapestryRPCClient interface {
	HelloCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*NodeMsg, error)
	GetNextHopCaller(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*NextHop, error)
	RegisterCaller(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*Ok, error)
	FetchCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*FetchedLocations, error)
	AddNodeCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Neighbors, error)
	RemoveBadNodesCaller(ctx context.Context, in *Neighbors, opts ...grpc.CallOption) (*Ok, error)
	AddNodeMulticastCaller(ctx context.Context, in *MulticastRequest, opts ...grpc.CallOption) (*Neighbors, error)
	TransferCaller(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*Ok, error)
	AddBackpointerCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Ok, error)
	RemoveBackpointerCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Ok, error)
	GetBackpointersCaller(ctx context.Context, in *BackpointerRequest, opts ...grpc.CallOption) (*Neighbors, error)
	NotifyLeaveCaller(ctx context.Context, in *LeaveNotification, opts ...grpc.CallOption) (*Ok, error)
	BlobStoreFetchCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DataBlob, error)
	TapestryStoreCaller(ctx context.Context, in *DataBlob, opts ...grpc.CallOption) (*Ok, error)
	TapestryLookupCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Neighbors, error)
}

type tapestryRPCClient struct {
	cc *grpc.ClientConn
}

func NewTapestryRPCClient(cc *grpc.ClientConn) TapestryRPCClient {
	return &tapestryRPCClient{cc}
}

func (c *tapestryRPCClient) HelloCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*NodeMsg, error) {
	out := new(NodeMsg)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/HelloCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) GetNextHopCaller(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*NextHop, error) {
	out := new(NextHop)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/GetNextHopCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) RegisterCaller(ctx context.Context, in *Registration, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/RegisterCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) FetchCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*FetchedLocations, error) {
	out := new(FetchedLocations)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/FetchCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) AddNodeCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Neighbors, error) {
	out := new(Neighbors)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/AddNodeCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) RemoveBadNodesCaller(ctx context.Context, in *Neighbors, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/RemoveBadNodesCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) AddNodeMulticastCaller(ctx context.Context, in *MulticastRequest, opts ...grpc.CallOption) (*Neighbors, error) {
	out := new(Neighbors)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/AddNodeMulticastCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) TransferCaller(ctx context.Context, in *TransferData, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/TransferCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) AddBackpointerCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/AddBackpointerCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) RemoveBackpointerCaller(ctx context.Context, in *NodeMsg, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/RemoveBackpointerCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) GetBackpointersCaller(ctx context.Context, in *BackpointerRequest, opts ...grpc.CallOption) (*Neighbors, error) {
	out := new(Neighbors)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/GetBackpointersCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) NotifyLeaveCaller(ctx context.Context, in *LeaveNotification, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/NotifyLeaveCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) BlobStoreFetchCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*DataBlob, error) {
	out := new(DataBlob)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/BlobStoreFetchCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) TapestryStoreCaller(ctx context.Context, in *DataBlob, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/TapestryStoreCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tapestryRPCClient) TapestryLookupCaller(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Neighbors, error) {
	out := new(Neighbors)
	err := grpc.Invoke(ctx, "/tapestry.TapestryRPC/TapestryLookupCaller", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TapestryRPC service

type TapestryRPCServer interface {
	HelloCaller(context.Context, *NodeMsg) (*NodeMsg, error)
	GetNextHopCaller(context.Context, *IdMsg) (*NextHop, error)
	RegisterCaller(context.Context, *Registration) (*Ok, error)
	FetchCaller(context.Context, *Key) (*FetchedLocations, error)
	AddNodeCaller(context.Context, *NodeMsg) (*Neighbors, error)
	RemoveBadNodesCaller(context.Context, *Neighbors) (*Ok, error)
	AddNodeMulticastCaller(context.Context, *MulticastRequest) (*Neighbors, error)
	TransferCaller(context.Context, *TransferData) (*Ok, error)
	AddBackpointerCaller(context.Context, *NodeMsg) (*Ok, error)
	RemoveBackpointerCaller(context.Context, *NodeMsg) (*Ok, error)
	GetBackpointersCaller(context.Context, *BackpointerRequest) (*Neighbors, error)
	NotifyLeaveCaller(context.Context, *LeaveNotification) (*Ok, error)
	BlobStoreFetchCaller(context.Context, *Key) (*DataBlob, error)
	TapestryStoreCaller(context.Context, *DataBlob) (*Ok, error)
	TapestryLookupCaller(context.Context, *Key) (*Neighbors, error)
}

func RegisterTapestryRPCServer(s *grpc.Server, srv TapestryRPCServer) {
	s.RegisterService(&_TapestryRPC_serviceDesc, srv)
}

func _TapestryRPC_HelloCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).HelloCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/HelloCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).HelloCaller(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_GetNextHopCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).GetNextHopCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/GetNextHopCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).GetNextHopCaller(ctx, req.(*IdMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_RegisterCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Registration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).RegisterCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/RegisterCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).RegisterCaller(ctx, req.(*Registration))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_FetchCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).FetchCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/FetchCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).FetchCaller(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_AddNodeCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).AddNodeCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/AddNodeCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).AddNodeCaller(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_RemoveBadNodesCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Neighbors)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).RemoveBadNodesCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/RemoveBadNodesCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).RemoveBadNodesCaller(ctx, req.(*Neighbors))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_AddNodeMulticastCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MulticastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).AddNodeMulticastCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/AddNodeMulticastCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).AddNodeMulticastCaller(ctx, req.(*MulticastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_TransferCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).TransferCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/TransferCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).TransferCaller(ctx, req.(*TransferData))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_AddBackpointerCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).AddBackpointerCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/AddBackpointerCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).AddBackpointerCaller(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_RemoveBackpointerCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).RemoveBackpointerCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/RemoveBackpointerCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).RemoveBackpointerCaller(ctx, req.(*NodeMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_GetBackpointersCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackpointerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).GetBackpointersCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/GetBackpointersCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).GetBackpointersCaller(ctx, req.(*BackpointerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_NotifyLeaveCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).NotifyLeaveCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/NotifyLeaveCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).NotifyLeaveCaller(ctx, req.(*LeaveNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_BlobStoreFetchCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).BlobStoreFetchCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/BlobStoreFetchCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).BlobStoreFetchCaller(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_TapestryStoreCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataBlob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).TapestryStoreCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/TapestryStoreCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).TapestryStoreCaller(ctx, req.(*DataBlob))
	}
	return interceptor(ctx, in, info, handler)
}

func _TapestryRPC_TapestryLookupCaller_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TapestryRPCServer).TapestryLookupCaller(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tapestry.TapestryRPC/TapestryLookupCaller",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TapestryRPCServer).TapestryLookupCaller(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _TapestryRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tapestry.TapestryRPC",
	HandlerType: (*TapestryRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloCaller",
			Handler:    _TapestryRPC_HelloCaller_Handler,
		},
		{
			MethodName: "GetNextHopCaller",
			Handler:    _TapestryRPC_GetNextHopCaller_Handler,
		},
		{
			MethodName: "RegisterCaller",
			Handler:    _TapestryRPC_RegisterCaller_Handler,
		},
		{
			MethodName: "FetchCaller",
			Handler:    _TapestryRPC_FetchCaller_Handler,
		},
		{
			MethodName: "AddNodeCaller",
			Handler:    _TapestryRPC_AddNodeCaller_Handler,
		},
		{
			MethodName: "RemoveBadNodesCaller",
			Handler:    _TapestryRPC_RemoveBadNodesCaller_Handler,
		},
		{
			MethodName: "AddNodeMulticastCaller",
			Handler:    _TapestryRPC_AddNodeMulticastCaller_Handler,
		},
		{
			MethodName: "TransferCaller",
			Handler:    _TapestryRPC_TransferCaller_Handler,
		},
		{
			MethodName: "AddBackpointerCaller",
			Handler:    _TapestryRPC_AddBackpointerCaller_Handler,
		},
		{
			MethodName: "RemoveBackpointerCaller",
			Handler:    _TapestryRPC_RemoveBackpointerCaller_Handler,
		},
		{
			MethodName: "GetBackpointersCaller",
			Handler:    _TapestryRPC_GetBackpointersCaller_Handler,
		},
		{
			MethodName: "NotifyLeaveCaller",
			Handler:    _TapestryRPC_NotifyLeaveCaller_Handler,
		},
		{
			MethodName: "BlobStoreFetchCaller",
			Handler:    _TapestryRPC_BlobStoreFetchCaller_Handler,
		},
		{
			MethodName: "TapestryStoreCaller",
			Handler:    _TapestryRPC_TapestryStoreCaller_Handler,
		},
		{
			MethodName: "TapestryLookupCaller",
			Handler:    _TapestryRPC_TapestryLookupCaller_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tapestry_rpc.proto",
}

func init() { proto.RegisterFile("tapestry_rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xdf, 0x4f, 0x13, 0x4b,
	0x14, 0x6e, 0xb7, 0x94, 0xb6, 0xa7, 0x85, 0x0b, 0x43, 0x2f, 0x34, 0xbd, 0xf7, 0xa1, 0xd9, 0xc4,
	0x04, 0xa2, 0x56, 0x03, 0x9a, 0xf0, 0xeb, 0x41, 0x40, 0x05, 0xa5, 0x14, 0x5d, 0xf1, 0xd9, 0x0c,
	0xdd, 0x03, 0x6c, 0xba, 0xec, 0xd4, 0x99, 0x69, 0xa5, 0xff, 0x96, 0x6f, 0xfe, 0x77, 0x66, 0xa6,
	0x33, 0xdd, 0x95, 0xdd, 0x12, 0xe2, 0x0b, 0xe9, 0x99, 0xf9, 0xbe, 0xf3, 0xe3, 0x9b, 0xf3, 0xb1,
	0x40, 0x24, 0x1d, 0xa0, 0x90, 0x7c, 0xfc, 0x8d, 0x0f, 0x7a, 0xed, 0x01, 0x67, 0x92, 0x91, 0xb2,
	0x3d, 0x73, 0x9f, 0x81, 0x73, 0xde, 0x27, 0x8b, 0xe0, 0xb0, 0x7e, 0x23, 0xdf, 0xca, 0xaf, 0x97,
	0x3d, 0x87, 0xf5, 0xc9, 0x2a, 0xcc, 0x73, 0xa4, 0x82, 0x45, 0x0d, 0xa7, 0x95, 0x5f, 0xaf, 0x78,
	0x26, 0x72, 0xd7, 0xa0, 0xf8, 0xc1, 0x3f, 0x13, 0xd7, 0x8a, 0x10, 0xf8, 0x9a, 0x50, 0xf1, 0x9c,
	0xc0, 0x77, 0x5f, 0x42, 0xf9, 0x2d, 0x95, 0xf4, 0x30, 0x64, 0x97, 0x84, 0xc0, 0x9c, 0x4f, 0x25,
	0xd5, 0xb7, 0x35, 0x4f, 0xff, 0x26, 0x4b, 0x50, 0xe8, 0xe3, 0xd8, 0x64, 0x53, 0x3f, 0xdd, 0x35,
	0x28, 0x9c, 0xe2, 0xd8, 0x5e, 0xe4, 0xe3, 0x8b, 0x2d, 0x28, 0x75, 0x99, 0x8f, 0xaa, 0x4a, 0x03,
	0x4a, 0xd4, 0xf7, 0x39, 0x0a, 0x61, 0x00, 0x36, 0x34, 0xf5, 0x9d, 0x69, 0xfd, 0x8f, 0x50, 0xea,
	0xe2, 0x9d, 0x3c, 0x61, 0x03, 0xf2, 0x04, 0xe6, 0x22, 0xbc, 0x93, 0x9a, 0x51, 0xdd, 0x5c, 0x6e,
	0xdb, 0x51, 0xdb, 0x26, 0xab, 0xa7, 0xaf, 0x55, 0xee, 0x1b, 0x2a, 0x14, 0x49, 0xa7, 0x29, 0x7b,
	0x36, 0x74, 0xcf, 0xa1, 0xe6, 0xe1, 0x75, 0x20, 0x24, 0xa7, 0x32, 0x60, 0x11, 0x79, 0x0e, 0xe5,
	0x2b, 0xce, 0x6e, 0x15, 0x7d, 0x76, 0xd2, 0x29, 0x24, 0x63, 0xd4, 0xaf, 0xb0, 0xf4, 0x1e, 0x65,
	0xef, 0x06, 0xfd, 0x0e, 0xeb, 0xe9, 0x9c, 0x42, 0x29, 0x1c, 0x08, 0x8f, 0x31, 0x69, 0x54, 0x37,
	0x11, 0xd9, 0x80, 0xf9, 0x11, 0x0d, 0x87, 0x28, 0x1a, 0x85, 0x56, 0x21, 0xbb, 0x94, 0x01, 0xb8,
	0xfb, 0x50, 0xe9, 0x62, 0x70, 0x7d, 0x73, 0xc9, 0xb8, 0x20, 0x2f, 0xa0, 0x12, 0xd9, 0xa0, 0x91,
	0x9f, 0x45, 0x8d, 0x31, 0xaa, 0xa9, 0xb3, 0x61, 0x28, 0x83, 0x1e, 0x15, 0xd2, 0xc3, 0xef, 0x43,
	0x14, 0x92, 0x3c, 0x85, 0x52, 0x84, 0x3f, 0x1e, 0x1e, 0xd4, 0x22, 0x48, 0x1d, 0x8a, 0x21, 0x8e,
	0x30, 0xd4, 0x93, 0x16, 0xbd, 0x49, 0xe0, 0xfe, 0xca, 0x43, 0xed, 0x82, 0xd3, 0x48, 0x5c, 0x21,
	0x57, 0x1b, 0xa1, 0x9e, 0x43, 0x49, 0xf3, 0xc0, 0x73, 0xa8, 0x6b, 0xf2, 0xca, 0x2c, 0x8d, 0xa3,
	0x5b, 0x6f, 0xc5, 0xb0, 0x64, 0xb2, 0xb6, 0xfa, 0xf3, 0x2e, 0x92, 0x7c, 0x3c, 0x59, 0xab, 0x66,
	0x07, 0x2a, 0xd3, 0xa3, 0xf4, 0x2a, 0x91, 0x0d, 0x28, 0x6a, 0xad, 0x74, 0x8b, 0xd5, 0xcd, 0x95,
	0x44, 0x71, 0xab, 0x83, 0x37, 0x41, 0xec, 0x3a, 0xdb, 0x79, 0xf7, 0x33, 0x90, 0x43, 0xda, 0xeb,
	0x0f, 0x58, 0x10, 0x49, 0xe4, 0x56, 0x94, 0x47, 0x0e, 0x90, 0x2d, 0x07, 0x83, 0xe5, 0x0e, 0xd2,
	0x11, 0x76, 0x99, 0x0c, 0xae, 0x82, 0xc9, 0xe3, 0x3f, 0x36, 0xe3, 0x16, 0x54, 0x39, 0x0e, 0x42,
	0xda, 0xc3, 0x5b, 0x8c, 0xa4, 0x99, 0x21, 0x03, 0x9d, 0x44, 0x6d, 0xfe, 0x2c, 0x41, 0xf5, 0xc2,
	0x20, 0xbc, 0x4f, 0x47, 0xe4, 0x35, 0x54, 0x4f, 0x30, 0x0c, 0xd9, 0x11, 0x0d, 0x43, 0xe4, 0x24,
	0x4d, 0x6f, 0xa6, 0x8f, 0xdc, 0x1c, 0xd9, 0x86, 0xa5, 0x63, 0x94, 0xc6, 0x52, 0x86, 0xfb, 0x4f,
	0x0c, 0xd4, 0xff, 0x04, 0xfe, 0x60, 0x4e, 0x90, 0x9a, 0xb9, 0x38, 0x71, 0x0f, 0x72, 0xc3, 0x5b,
	0x8d, 0x61, 0x49, 0x5f, 0x35, 0x6b, 0xf1, 0xf9, 0x79, 0xdf, 0xcd, 0x91, 0x5d, 0xa8, 0x6a, 0x9b,
	0x18, 0xda, 0x42, 0x7c, 0x7d, 0x8a, 0xe3, 0x66, 0x33, 0x0e, 0xef, 0x9b, 0xc9, 0xcd, 0x91, 0x1d,
	0x58, 0x38, 0xf0, 0x7d, 0xd5, 0xff, 0xec, 0x41, 0xb3, 0x9e, 0xdf, 0xcd, 0x91, 0x3d, 0xa8, 0x7b,
	0x78, 0xcb, 0x46, 0x78, 0x48, 0x75, 0x02, 0x61, 0x32, 0x64, 0xc1, 0x53, 0x3d, 0x9f, 0xc2, 0xaa,
	0xa9, 0x3b, 0x35, 0x93, 0xa1, 0x27, 0xfa, 0xbd, 0xef, 0xb3, 0x59, 0x9d, 0x6c, 0xc3, 0xa2, 0xdd,
	0xf6, 0xb4, 0x74, 0x49, 0x1f, 0xa4, 0xda, 0xd8, 0x81, 0xfa, 0x81, 0xef, 0x27, 0x96, 0x77, 0xb6,
	0x0a, 0xf7, 0xa9, 0xfb, 0xb0, 0x66, 0xc7, 0xff, 0x0b, 0x76, 0x07, 0xfe, 0x3d, 0x46, 0x99, 0xa0,
	0x5a, 0xf5, 0xfe, 0x8f, 0x81, 0x69, 0x4f, 0xcd, 0x12, 0xe0, 0x0d, 0x2c, 0x6b, 0xa3, 0x8c, 0xb5,
	0x67, 0x4c, 0xa6, 0xff, 0x62, 0x6c, 0xca, 0x4a, 0xa9, 0x7e, 0xf6, 0xa0, 0xae, 0xbe, 0x41, 0x5f,
	0x24, 0xe3, 0xf8, 0xc0, 0x32, 0x91, 0x38, 0xb4, 0x9f, 0x2d, 0xad, 0xe2, 0x8a, 0xb5, 0x8e, 0x4e,
	0x60, 0xb8, 0x19, 0xe0, 0x0c, 0x15, 0xeb, 0x96, 0xda, 0x61, 0xac, 0x3f, 0x1c, 0x64, 0xd7, 0xcd,
	0x9e, 0xfb, 0x72, 0x5e, 0x7f, 0x95, 0xb7, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xa8, 0xb1,
	0xb2, 0xab, 0x07, 0x00, 0x00,
}
